const content=document.querySelector('#content'),q=document.querySelector('#q'),chips=document.querySelector('#chips');
let beans=[]; try{beans=await fetch('./data/beans.json').then(r=>r.json())}catch(e){content.innerHTML='<p>資料讀取失敗，請透過 GitHub Pages 或本機伺服器開啟。</p>'}
const esc=s=>String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function card(b){return `<article class="card" data-id="${b.id}"><span class="eyebrow">${esc(b.country)} · ${esc(b.region)}</span><h4>${esc(b.name)}</h4><p>${esc(b.zh)} · ${esc(b.type)}<br>${esc(b.process)} · ${esc(b.altitude)}</p><div class="tags">${b.flavors.slice(0,3).map(x=>`<span class="tag">${esc(x)}</span>`).join('')}</div></article>`}
function section(title,sub,items){content.innerHTML=`<div class="section-title"><div><span class="eyebrow">COFFEE ATLAS</span><h3>${title}</h3></div><small>${sub}</small></div><div class="grid">${items.map(card).join('')}</div>`;bindCards()}
function bindCards(){document.querySelectorAll('.card').forEach(el=>el.onclick=()=>detail(beans.find(b=>b.id===el.dataset.id)))}
function detail(b){content.innerHTML=`<div class="detail"><span class="eyebrow">${b.country} · ${b.region}</span><h2>${b.name}</h2><p>${b.zh} · ${b.type}</p><p>${b.intro}</p><div class="tags">${b.flavors.map(x=>`<span class="tag">${x}</span>`).join('')}</div><p><b>海拔</b> ${b.altitude}<br><b>品種</b> ${b.variety}<br><b>處理法</b> ${b.process}</p><div class="meters">${[['甜感',b.sweet],['酸質',b.acid],['醇厚',b.body]].map(([n,v])=>`<div class="meter"><span>${n}</span><div class="bar"><i style="width:${v*20}%"></i></div><b>${v}/5</b></div>`).join('')}</div></div>`}
function search(term){let t=term.trim().toLowerCase();let r=!t?beans:beans.filter(b=>Object.values(b).flat().join(' ').toLowerCase().includes(t));section('Search',`${r.length} results`,r)}
function learn(){content.innerHTML=`<div class="section-title"><div><span class="eyebrow">LEARN</span><h3>咖啡小知識</h3></div><small>V1</small></div><div class="grid">${[['手沖 Pour Over','15g / 240g','90–94°C','2:30–3:00'],['French Press','15g / 240g','90–94°C','4:00'],['AeroPress','15g / 220g','85–92°C','1:30–2:30']].map(x=>`<article class="card"><span class="eyebrow">BREW GUIDE</span><h4>${x[0]}</h4><p>粉水 ${x[1]}<br>水溫 ${x[2]}<br>時間 ${x[3]}</p><div class="tags"><span class="tag">淺焙</span><span class="tag">中焙</span><span class="tag">深焙</span></div></article>`).join('')}</div>`}
function roasters(){content.innerHTML=`<div class="section-title"><div><span class="eyebrow">SEPTEMBER EDIT</span><h3>Roasters of the Month</h3></div><small>Coming next</small></div><div class="detail"><h2>每月 3–5 家精選</h2><p>這一區會用「咖啡雜誌」而不是店家資料庫的方式呈現：建築、飲品、餐食、照片與短文。V1 骨架先保留，正式店家與授權圖片下一階段加入。</p></div>`}
function view(v){document.querySelectorAll('nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===v)); if(v==='learn')learn(); else if(v==='roasters')roasters(); else if(v==='search')search(q.value); else section('Explore','Ethiopia first',beans)}
document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>view(b.dataset.view));q.addEventListener('input',()=>{view('search')});chips.innerHTML=['Ethiopia','Natural','Geisha','花香'].map(x=>`<button>${x}</button>`).join('');chips.querySelectorAll('button').forEach(b=>b.onclick=()=>{q.value=b.textContent;view('search')});view('explore');
